person = {"name" :"Param patel ","age":18,"weight":45.45}
print(person)
# person.clear()
# print(person)
person2 = person.copy()
print(person2)
temp = person.items()
print(temp)
temp = person.keys()
print(temp)
temp = person.pop("age")
print(temp)
print(person)
temp = person.popitem()
print(temp)
print(person)
print(person.keys())
person['gender'] = True
print(person)