# example of list method
numbers = [10,20,30,40,50,60,70,80,90,100,10]
fruits = ['Mango','Oragne',"Apple"]
names =['param','sahil','pratham','divya','diya']
print(fruits)
print(numbers)
numbers.append(110)
numbers.append(120)
print(numbers)
fruits.extend(numbers)
print(fruits)
numbers.insert(0,5)
print(numbers)
numbers.remove(50)
print(numbers)
temp = fruits.pop(2)
print(fruits)
print(temp)
fruits.clear()
print(fruits)
# del fruits
# print(fruits)
temp = numbers.index(100)
print(temp)
temp = numbers.count(10)
print(temp)
names.sort()
print(names)
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
my_numbers = numbers.copy()
print(my_numbers)